language: go

go:
  - "1.10"

before_script:
  - > 
    go get 
    github.com/terraform-providers/terraform-provider-aws 
    github.com/terraform-providers/terraform-provider-template
    github.com/terraform-providers/terraform-provider-vsphere 

script:
  - go test -v -cover ./...
  - go install
  - $GOPATH/bin/tfprovlint lint github.com/terraform-providers/terraform-provider-aws
  - $GOPATH/bin/tfprovlint lint github.com/terraform-providers/terraform-provider-template
  - $GOPATH/bin/tfprovlint lint github.com/terraform-providers/terraform-provider-vsphere
